FROM golang:1.26.1 AS build
RUN CGO_ENABLED=0 go install github.com/fujiwara/simplemq-cli/cmd/simplemq-localserver@latest

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends wget && rm -rf /var/lib/apt/lists/*
COPY --from=build /go/bin/simplemq-localserver /usr/local/bin/
EXPOSE 18080
CMD ["simplemq-localserver"]
